<?php


namespace Php127\Tests\Provider;


use Php127\Douyin\Provider\Kuaishou;
use PHPUnit\Framework\TestCase;

class KuaishouTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->url = 'https://v.kuaishou.com/gcNIRW';
    }

    public function testGetData(){

        $app = new Kuaishou($this->url);

    }
}