<?php

namespace Analysis;

use Php127\Douyin\Analysis\DouyinApi;
use PHPUnit\Framework\TestCase;

class DouyinApiTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->url = 'https://v.douyin.com/eeYy4Yo/';
    }

    public function testGetData()
    {
        $res = DouyinApi::lmengcity($this->url);
        $this->assertTrue(!empty($res));
    }
}
