<?php

namespace Php127\Tests\Analysis;

use Php127\Douyin\Factory;
use PHPUnit\Framework\TestCase;

class DouyinTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->url = 'https://v.douyin.com/exYnGc9/';
    }

    public function testGetData()
    {
        $app = Factory::douyin($this->url);
        $data = $app->getData();

        $this->assertTrue(!empty($data['url']));
        $this->assertTrue(!empty($data['img']));
        $this->assertTrue(!empty($data['music']));
        $this->assertTrue(!empty($data['title']));
    }

    public function testGetTitle()
    {
        $app = Factory::douyin($this->url);
        $this->assertTrue(!empty($app->getTitle()));
    }

    public function testGetUrl()
    {
        $app = Factory::douyin($this->url);
        $this->assertTrue(!empty($app->getUrl()));
    }

    public function testGetImg()
    {
        $app = Factory::douyin($this->url);
        $this->assertTrue(!empty($app->getImg()));
    }

    public function testGetMusic()
    {
        $app = Factory::douyin($this->url);
        $this->assertTrue(!empty($app->getMusic()));
    }
}
